# turing_garden = Garden.create!(name: 'Turing Community Garden', organic: true)
# library_garden = Garden.create!(name: 'Public Library Garden', organic: true)
# other_garden = Garden.create!(name: 'Main Street Garden', organic: false)
#
# turing_garden.plots.create!(number: 25, size: "Large", direction: "East")
# turing_garden.plots.create!(number: 26, size: "Small", direction: "West")
# library_garden.plots.create!(number: 2, size: "Small", direction: "South")
# other_garden.plots.create!(number: 738, size: "Medium", direction: "West")

garden1 = Garden.create!(name: "My Garden", organic: true)
garden2 = Garden.create!(name: "Not My Garden", organic: false)

plot1 = Plot.create!(number: 1, size: "Small", direction: "North", garden_id: garden1.id)
plot2 = Plot.create!(number: 2, size: "Medium", direction: "East", garden_id: garden1.id)
plot3 = Plot.create!(number: 3, size: "Large", direction: "South", garden_id: garden1.id)
plot4 = Plot.create!(number: 4, size: "Extra Large", direction: "West", garden_id: garden2.id)

plant1 = Plant.create!(name: "Marigold", description: "American Marigold", days_to_harvest: 45)
plant2 = Plant.create!(name: "Vinca", description: "Apocynceae", days_to_harvest: 50)
plant3 = Plant.create!(name: "Beautybush", description: "Beautiful", days_to_harvest: 55)
plant4 = Plant.create!(name: "Fountain Grass", description: "Poacaea", days_to_harvest: 60)
plotplant1 = PlantPlot.create!(plot_id: plot1.id, plant_id: plant1.id)
plotplant2 = PlantPlot.create!(plot_id: plot1.id, plant_id: plant2.id)
plotplant3 = PlantPlot.create!(plot_id: plot1.id, plant_id: plant3.id)
plotplant4 = PlantPlot.create!(plot_id: plot2.id, plant_id: plant2.id)
plotplant5 = PlantPlot.create!(plot_id: plot2.id, plant_id: plant4.id)
